### ISSUE TITLE
NullPointerException if bedLocation is in unloaded world

### ISSUE THREAD

**Issue by TimonMi** [PaperMC/PaperLib#30] opened 2020-09-06 18:20 UTC
Title says it all:
`
java.lang.NullPointerException: null
    at com.earth2me.essentials.paperlib.features.asyncchunks.AsyncChunksPaper_15.getChunkAtAsync(AsyncChunksPaper_15.java:11) ~[?:?]
    at com.earth2me.essentials.paperlib.environments.Environment.getChunkAtAsync(Environment.java:84) ~[?:?]
    at com.earth2me.essentials.paperlib.PaperLib.getChunkAtAsync(PaperLib.java:146) ~[?:?]
    at com.earth2me.essentials.paperlib.features.bedspawnlocation.BedSpawnLocationPaper.getBedSpawnLocationAsync(BedSpawnLocationPaper.java:17) ~[?:?]
    at com.earth2me.essentials.paperlib.environments.Environment.getBedSpawnLocationAsync(Environment.java:104) ~[?:?]
    at com.earth2me.essentials.paperlib.PaperLib.getBedSpawnLocationAsync(PaperLib.java:201) ~[?:?]
    at com.earth2me.essentials.EssentialsPlayerListener.updateCompass(EssentialsPlayerListener.java:412) ~[?:?]
    at com.earth2me.essentials.EssentialsPlayerListener.access$500(EssentialsPlayerListener.java:46) ~[?:?]
    at com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask.run(EssentialsPlayerListener.java:280) ~[?:?]
    at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-387]
    at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-387]
    at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1265) ~[patched_1.15.2.jar:git-Paper-387]
    at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-387]
    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1182) ~[patched_1.15.2.jar:git-Paper-387]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-387]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]`

https://github.com/PaperMC/PaperLib/blob/1c3c36b188794e7adc48f87866c0ba806151d46b/src/main/java/io/papermc/lib/features/bedspawnlocation/BedSpawnLocationPaper.java#L14
Here we do not check whether or not the World actually exists.
According to the getPotentialBedLocation documentation:

> Gets the last known location of a player's bed. This does not preform any check if the bed is still valid and does not load any chunks.
https://github.com/PaperMC/Paper/blob/cebec202f85651f7a700e2af55c926d55ff4fc30/Spigot-Server-Patches/0514-Potential-bed-API.patch#L8

So in case the world does not exist it should return null directly, else it will throw the exception.

Hope i made the fix easier for you guys with my research ;)

**Comment by JRoy** [comment] 2020-09-06 18:57
Can you reproduce this on latest Paper? it should be fixed since https://github.com/PaperMC/Paper/pull/4238

**Comment by TimonMi** [comment] 2020-09-06 19:01
We are running Paper git-Paper-347
It's only fixed in the 1.16 release, but i may be wrong.

**Closed** 2020-09-28 11:42 UTC
